version: '3.1'
services:
  postgres:
    container_name: ${POSTGRES_DB}-postgres
    image: postgres:13.3-alpine
    restart: always
    volumes:
      - ${POSTGRES_DATA_DIR}:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}      
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"

networks:
  default:
    external:
      name: ${POSTGRES_USER}
